# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'multiple_image' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for multiple_image
 	pod "BSImagePicker", "~> 3.1"

end
